### ISSUE TITLE
show screenshot

### ISSUE THREAD

**Issue by mikdmst1** [NiziL/lightdm-micro-greeter#8]
subj

**Comment by NiziL** [comment]
Actually a neat idea, but this is a spartan UI right now (and will probably be forever).
So there's not much to be shown : a basic gtk entry over an image...

I'll take some time this week to update the README :)

**Comment by NiziL** [comment]
Sorry about the delay !
Actually, it has been quite a pain to get a nice screenshot using xephyr and `lightdm --test-mode`, i3 really want it as a floating window, which kinda mess the layout.

And btw, I'm currently playing around fyne, and expect to push a big refactoring soon.

I'll keep the issue open, as a reminder, but don't expect a nice screenshot before that.

**Comment by NiziL** [comment]
So actually using `dm-tool` was the way to go, here you are :)
